name: darfy_app
description: Prototype app demonstrating mock AI for accounting notes.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  camera: ^0.11.0
  go_router: ^13.0.0
  introduction_screen: ^3.1.0
  modal_bottom_sheet:
  rive: ^0.13.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/animations/darfy_idle.json
